<template><div><p>[toc]</p>
<h2 id="一、准备工作" tabindex="-1"><a class="header-anchor" href="#一、准备工作"><span>一、准备工作</span></a></h2>
<h3 id="安装edge" tabindex="-1"><a class="header-anchor" href="#安装edge"><span>安装Edge</span></a></h3>
<p><a href="https://www.microsoft.com/zh-cn/edge/download?form=MA13FJ" target="_blank" rel="noopener noreferrer">下载 Microsoft Edge<ExternalLinkIcon/></a></p>
<p><img src="https://djm-1317856319.cos.ap-shanghai.myqcloud.com/djm-1317856319/图片.png" alt=""></p>
<h3 id="安装vs-code" tabindex="-1"><a class="header-anchor" href="#安装vs-code"><span>安装VS Code</span></a></h3>
<p><a href="https://code.visualstudio.com/" target="_blank" rel="noopener noreferrer">下载 Visual Studio Code<ExternalLinkIcon/></a></p>
<h3 id="安装vs-code插件" tabindex="-1"><a class="header-anchor" href="#安装vs-code插件"><span>安装VS Code插件</span></a></h3>
<ul>
<li>
<p>汉化
<img src="https://djm-1317856319.cos.ap-shanghai.myqcloud.com/djm-1317856319/Pasted image 20240728130824.png" alt=""></p>
</li>
<li>
<p>图片预览
<img src="https://djm-1317856319.cos.ap-shanghai.myqcloud.com/djm-1317856319/Pasted image 20240728125834.png" alt=""></p>
</li>
<li>
<p>自动加标签
<img src="https://djm-1317856319.cos.ap-shanghai.myqcloud.com/djm-1317856319/Pasted image 20240728131121.png" alt=""></p>
</li>
<li>
<p>自动重命名
<img src="https://djm-1317856319.cos.ap-shanghai.myqcloud.com/djm-1317856319/Pasted image 20240728130013.png" alt=""></p>
</li>
<li>
<p>实时更新
<img src="https://djm-1317856319.cos.ap-shanghai.myqcloud.com/djm-1317856319/Pasted image 20240728130945.png" alt=""></p>
</li>
<li>
<p>浏览器中打开
<img src="https://djm-1317856319.cos.ap-shanghai.myqcloud.com/djm-1317856319/Pasted image 20240728131027.png" alt=""></p>
</li>
</ul>
<h2 id="二、html基础" tabindex="-1"><a class="header-anchor" href="#二、html基础"><span>二、HTML基础</span></a></h2>
<h3 id="文本声明" tabindex="-1"><a class="header-anchor" href="#文本声明"><span>文本声明</span></a></h3>
<p><strong>作用</strong>：告诉浏览器当前网页的版本
<strong>写法</strong>：<code v-pre>&lt;!DOCTYPE html&gt;</code></p>
<h3 id="字符编码" tabindex="-1"><a class="header-anchor" href="#字符编码"><span>字符编码</span></a></h3>
<p><strong>作用</strong>：存储时，对数据进行编码,读取时，对数据进行解码
<strong>写法</strong>：<code v-pre>&lt;meta charset=&quot;UTF-8&quot;/&gt;</code>
<strong>属性</strong>：</p>
<table>
<thead>
<tr>
<th>charset</th>
<th>解释</th>
</tr>
</thead>
<tbody>
<tr>
<td>ASCII</td>
<td>大写字母、小写字母、数字、一些符号，共计128个</td>
</tr>
<tr>
<td>ISO 8859-1</td>
<td>在 ASCII 基础上，扩充了一些希腊字符等，共计是256个</td>
</tr>
<tr>
<td>GB2312</td>
<td>继续扩充，收录了 6763 个常用汉字、682个字符</td>
</tr>
<tr>
<td>GBK</td>
<td>收录了的汉字和符号达到 20000+ ，支持繁体中文</td>
</tr>
<tr>
<td>UTF-8</td>
<td>包含世界上所有语言的：所有文字与符号。—— 很常用</td>
</tr>
</tbody>
</table>
<pre><code>存储时，务必采用合适的字符编码
存储时采用哪种方式编码 ，读取时就采用哪种方式解码
编写 html 文件时，也都统一用 UFT-8 编码
</code></pre>
<h3 id="设置语言" tabindex="-1"><a class="header-anchor" href="#设置语言"><span>设置语言</span></a></h3>
<p><strong>作用</strong>：让浏览器显示对应的翻译提示。有利于搜索引擎优化
<strong>写法</strong>：<code v-pre>&lt;html lang=&quot;zh-CN&quot;&gt;</code>
<strong>属性</strong>：</p>
<table>
<thead>
<tr>
<th>lang</th>
<th>解释</th>
</tr>
</thead>
<tbody>
<tr>
<td>zh-CN</td>
<td>中文-中国大陆（简体中文）</td>
</tr>
<tr>
<td>zh-TW</td>
<td>中文-中国台湾（繁体中文）</td>
</tr>
<tr>
<td>zh</td>
<td>中文</td>
</tr>
<tr>
<td>en-US</td>
<td>英语-美国</td>
</tr>
<tr>
<td>en-GB</td>
<td>英语-英国</td>
</tr>
</tbody>
</table>
<h3 id="块元素" tabindex="-1"><a class="header-anchor" href="#块元素"><span>块元素</span></a></h3>
<p><strong>作用</strong>：独占一行</p>
<h3 id="行内元素" tabindex="-1"><a class="header-anchor" href="#行内元素"><span>行内元素</span></a></h3>
<p><strong>作用</strong>：不独占一行</p>
<h3 id="双标签" tabindex="-1"><a class="header-anchor" href="#双标签"><span>双标签</span></a></h3>
<p><strong>作用</strong>：成对出现的标签，分为开始标签和结束标签</p>
<h3 id="单标签" tabindex="-1"><a class="header-anchor" href="#单标签"><span>单标签</span></a></h3>
<p><strong>作用</strong>：只有开始标签，没有结束标签</p>
<h3 id="注释" tabindex="-1"><a class="header-anchor" href="#注释"><span>注释</span></a></h3>
<p><strong>作用</strong>：对代码进行解释和说明
<strong>写法</strong>：<code v-pre>&lt;!-- 这是注释 --&gt;</code></p>
<h3 id="路径" tabindex="-1"><a class="header-anchor" href="#路径"><span>路径</span></a></h3>
<p><strong>作用</strong>：文件位置
<strong>属性</strong>：</p>
<table>
<thead>
<tr>
<th>符号</th>
<th>解释</th>
</tr>
</thead>
<tbody>
<tr>
<td>./</td>
<td>同级（可省略）</td>
</tr>
<tr>
<td>../</td>
<td>上一级</td>
</tr>
</tbody>
</table>
<h3 id="元信息" tabindex="-1"><a class="header-anchor" href="#元信息"><span>元信息</span></a></h3>
<p><strong>作用</strong>：
<strong>写法</strong>：</p>
<h3 id="全局属性" tabindex="-1"><a class="header-anchor" href="#全局属性"><span>全局属性</span></a></h3>
<p><strong>作用</strong>：基本上都能加的属性
<strong>属性</strong>：</p>
<table>
<thead>
<tr>
<th>属性名</th>
<th>含义</th>
</tr>
</thead>
<tbody>
<tr>
<td>id</td>
<td>给标签指定唯一标识</td>
</tr>
<tr>
<td>class</td>
<td>给标签指定类名</td>
</tr>
<tr>
<td>style</td>
<td>给标签设置CSS样式</td>
</tr>
<tr>
<td>dir</td>
<td>内容的方向，值：ltr、rtl</td>
</tr>
<tr>
<td>title</td>
<td>给标签设置一个文字提示</td>
</tr>
<tr>
<td>lang</td>
<td>给标签指定语言</td>
</tr>
</tbody>
</table>
<pre><code>id不能重复
</code></pre>
<h3 id="实体字符" tabindex="-1"><a class="header-anchor" href="#实体字符"><span>实体字符</span></a></h3>
<table>
<thead>
<tr>
<th>符号</th>
<th>描述</th>
<th>实体名称</th>
<th>实体编号</th>
</tr>
</thead>
<tbody>
<tr>
<td></td>
<td>空格</td>
<td>&amp;nbsp;</td>
<td>&amp;#160;</td>
</tr>
<tr>
<td>&lt;</td>
<td>小于号</td>
<td>&amp;lt;</td>
<td>&amp;#60;</td>
</tr>
<tr>
<td>&gt;</td>
<td>大于号</td>
<td>&amp;gt;</td>
<td>&amp;#62;</td>
</tr>
<tr>
<td>&amp;</td>
<td>和号</td>
<td>&amp;amp;</td>
<td>&amp;#38;</td>
</tr>
<tr>
<td>lI</td>
<td>引号</td>
<td>&amp;quot;</td>
<td>&amp;#34;</td>
</tr>
<tr>
<td>´</td>
<td>反引号</td>
<td>&amp;acute;</td>
<td>&amp;#180;</td>
</tr>
<tr>
<td>4</td>
<td>分(cent)</td>
<td>&amp;cent;</td>
<td>&amp;#162;</td>
</tr>
<tr>
<td>f</td>
<td>镑(pound)</td>
<td>&amp;pound;</td>
<td>&amp;#163;</td>
</tr>
<tr>
<td>¥</td>
<td>元(yen)</td>
<td>&amp;yen;</td>
<td>&amp;#165;</td>
</tr>
<tr>
<td>E</td>
<td>欧元(euro)</td>
<td>&amp;euro;</td>
<td>&amp;#8364;</td>
</tr>
<tr>
<td>O</td>
<td>版权(copyright)</td>
<td>&amp;copy;</td>
<td>&amp;#169;</td>
</tr>
<tr>
<td>@</td>
<td>注册商标</td>
<td>&amp;reg;</td>
<td>&amp;#174;</td>
</tr>
<tr>
<td>TM</td>
<td>商标</td>
<td>&amp;trade;</td>
<td>&amp;#8482;</td>
</tr>
<tr>
<td>×</td>
<td>乘号</td>
<td>&amp;times</td>
<td>&amp;#215;</td>
</tr>
<tr>
<td>÷</td>
<td>除号</td>
<td>&amp;divide;</td>
<td>&amp;#247;</td>
</tr>
</tbody>
</table>
<h2 id="三、html标签" tabindex="-1"><a class="header-anchor" href="#三、html标签"><span>三、HTML标签</span></a></h2>
<h3 id="排版标签" tabindex="-1"><a class="header-anchor" href="#排版标签"><span>排版标签</span></a></h3>
<p><strong>作用</strong>：排版布局，分清主次
<strong>写法</strong>：<code v-pre>&lt;h1&gt;&lt;/h1&gt;</code></p>
<table>
<thead>
<tr>
<th>标签名</th>
<th>标签含义</th>
<th>单/双标签</th>
<th>块/行</th>
</tr>
</thead>
<tbody>
<tr>
<td>h1~h6</td>
<td>标题</td>
<td>双</td>
<td>块</td>
</tr>
<tr>
<td>p</td>
<td>段落</td>
<td>双</td>
<td>块</td>
</tr>
<tr>
<td>div</td>
<td>无含义用于整体布局</td>
<td>双</td>
<td>块</td>
</tr>
<tr>
<td>em</td>
<td>着重内容</td>
<td>双</td>
<td>行</td>
</tr>
<tr>
<td>strong</td>
<td>更重要的内容</td>
<td>双</td>
<td>行</td>
</tr>
<tr>
<td>span</td>
<td>没有语义的通用容器</td>
<td>双</td>
<td>行</td>
</tr>
<tr>
<td>strong</td>
<td>加粗</td>
<td>双</td>
<td>行</td>
</tr>
<tr>
<td>del</td>
<td>删除线</td>
<td>双</td>
<td>行</td>
</tr>
<tr>
<td>ins</td>
<td>下划线</td>
<td>双</td>
<td>行</td>
</tr>
<tr>
<td>br</td>
<td>换行</td>
<td>单</td>
<td>块</td>
</tr>
<tr>
<td>hr</td>
<td>分隔</td>
<td>单</td>
<td>块</td>
</tr>
<tr>
<td>pre</td>
<td>按原文显示</td>
<td>双</td>
<td>块</td>
</tr>
</tbody>
</table>
<pre><code>h1 只能写一个
h1~h6 不能互相嵌套
</code></pre>
<h3 id="图片标签" tabindex="-1"><a class="header-anchor" href="#图片标签"><span>图片标签</span></a></h3>
<p><strong>作用</strong>：插入图片
<strong>写法</strong>：<code v-pre>&lt;img src=&quot;&quot; alt=&quot;&quot;&gt;</code>
<strong>属性</strong>：</p>
<table>
<thead>
<tr>
<th>img</th>
<th>解释</th>
</tr>
</thead>
<tbody>
<tr>
<td>src</td>
<td>图片路径</td>
</tr>
<tr>
<td>alt</td>
<td>图片描述</td>
</tr>
<tr>
<td>width</td>
<td>图片宽度</td>
</tr>
<tr>
<td>height</td>
<td>图片高度</td>
</tr>
<tr>
<td>border</td>
<td>图片边框</td>
</tr>
</tbody>
</table>
<h3 id="超链接标签" tabindex="-1"><a class="header-anchor" href="#超链接标签"><span>超链接标签</span></a></h3>
<p><strong>作用</strong>：从当前页面进行跳转
<strong>写法</strong>：<code v-pre>&lt;a href=&quot;&quot; id=&quot;&quot; name=&quot;&quot; traget=&quot;&quot;&gt;&lt;/a&gt;</code>
<strong>属性</strong>：</p>
<table>
<thead>
<tr>
<th>a</th>
<th>解释</th>
</tr>
</thead>
<tbody>
<tr>
<td>href</td>
<td>指定要跳转到的具体目标</td>
</tr>
<tr>
<td>target</td>
<td>控制跳转时如何打开页面<br> _self ：在本窗口打开。</br> _blank ：在新窗口打开。</td>
</tr>
<tr>
<td>id</td>
<td>元素的唯一 标识，可用于设置锚点。</td>
</tr>
<tr>
<td>name</td>
<td>元素的名字,也能设置锚点.</td>
</tr>
</tbody>
</table>
<h3 id="列表" tabindex="-1"><a class="header-anchor" href="#列表"><span>列表</span></a></h3>
<p><strong>分类</strong>：有序列表、无序列表、自定义列表
<strong>写法</strong>：<code v-pre>&lt;ol&gt; &lt;ul&gt; &lt;dl&gt;</code></p>
<h3 id="表格" tabindex="-1"><a class="header-anchor" href="#表格"><span>表格</span></a></h3>
<p><strong>组成</strong>：表格标题、表格头部、表格主体、表格脚注
<strong>属性</strong>：</p>
<table>
<thead>
<tr>
<th>表格</th>
<th>解释</th>
</tr>
</thead>
<tbody>
<tr>
<td>table</td>
<td>表格</td>
</tr>
<tr>
<td>caption</td>
<td>表格标题</td>
</tr>
<tr>
<td>thead</td>
<td>表格头部</td>
</tr>
<tr>
<td>tbody</td>
<td>表格主体</td>
</tr>
<tr>
<td>tfoot</td>
<td>表格注脚</td>
</tr>
<tr>
<td>tr</td>
<td>每一行</td>
</tr>
<tr>
<td>th</td>
<td>一个单元格</td>
</tr>
<tr>
<td>td</td>
<td>一个单元格</td>
</tr>
<tr>
<td>rowspan</td>
<td>要跨的行数</td>
</tr>
<tr>
<td>colspan</td>
<td>要跨的列数</td>
</tr>
</tbody>
</table>
<pre><code>表格头部中用th，表格主体、表格脚注中用td
</code></pre>
<h3 id="表单" tabindex="-1"><a class="header-anchor" href="#表单"><span>表单</span></a></h3>
<h2 id="问答" tabindex="-1"><a class="header-anchor" href="#问答"><span>问答</span></a></h2>
<h3 id="语义化标签的好处" tabindex="-1"><a class="header-anchor" href="#语义化标签的好处"><span>语义化标签的好处</span></a></h3>
<ol>
<li>提高用户体验</li>
<li>有利于SEO，方便搜索</li>
<li>具有可读性</li>
<li>代码结构更好</li>
</ol>
<h3 id="重排和重绘" tabindex="-1"><a class="header-anchor" href="#重排和重绘"><span>重排和重绘</span></a></h3>
<p>重排：当页面元素位置发生变化，浏览器会重新计算页面元素位置，然后重新渲染页面。</p>
<ol>
<li>增删dom元素</li>
<li>位置改变</li>
<li>尺寸改变</li>
<li>内容改变</li>
<li>第一次渲染</li>
</ol>
<p>重绘：当页面元素外观发生变化，浏览器会重新渲染页面元素。</p>
<ol>
<li>布局未变，外观改变</li>
<li>样式改变</li>
</ol>
<h2 id="一、html基础" tabindex="-1"><a class="header-anchor" href="#一、html基础"><span>一、HTML基础</span></a></h2>
<h3 id="_1-文档基本格式" tabindex="-1"><a class="header-anchor" href="#_1-文档基本格式"><span>1.文档基本格式</span></a></h3>
<div class="language-text line-numbers-mode" data-ext="text" data-title="text"><pre v-pre class="language-text"><code>&lt;!DOCTYPE html> 
&lt;html lang="zh-CN"> 
&lt;head> 
&lt;meta charset="UTF-8"> 
&lt;title>我是一个标题&lt;/title> 
&lt;/head> 
&lt;body> 
&lt;/body> 
&lt;/html>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_2-基本概念" tabindex="-1"><a class="header-anchor" href="#_2-基本概念"><span>2.基本概念</span></a></h3>
<table>
<thead>
<tr>
<th>概念</th>
<th>描述</th>
</tr>
</thead>
<tbody>
<tr>
<td>单标签</td>
<td>只能有一个开始标记</td>
</tr>
<tr>
<td>双标签</td>
<td>开始标记和结束标记</td>
</tr>
<tr>
<td>行内元素</td>
<td>独占一行</td>
</tr>
<tr>
<td>块元素</td>
<td>不独占一行</td>
</tr>
<tr>
<td>相对路径</td>
<td>当前目录</td>
</tr>
<tr>
<td>绝对路径</td>
<td>全路径</td>
</tr>
</tbody>
</table>
<h3 id="_3-特殊字符" tabindex="-1"><a class="header-anchor" href="#_3-特殊字符"><span>3.特殊字符</span></a></h3>
<table>
<thead>
<tr>
<th>符号</th>
<th>含义</th>
<th>实体名称</th>
<th>实体编号</th>
</tr>
</thead>
<tbody>
<tr>
<td></td>
<td>空格</td>
<td>&amp;nbsp;</td>
<td>&amp;#160;</td>
</tr>
<tr>
<td>&lt;</td>
<td>小于号</td>
<td>&amp;lt;</td>
<td>&amp;#60;</td>
</tr>
<tr>
<td>&gt;</td>
<td>大于号</td>
<td>&amp;gt;</td>
<td>&amp;#62;</td>
</tr>
<tr>
<td>&amp;</td>
<td>和号</td>
<td>&amp;amp;</td>
<td>&amp;#38;</td>
</tr>
<tr>
<td>&quot;</td>
<td>引号</td>
<td>&amp;quot;</td>
<td>&amp;#34;</td>
</tr>
<tr>
<td>`</td>
<td>反引号</td>
<td>&amp;acute;</td>
<td>&amp;#180;</td>
</tr>
<tr>
<td>£</td>
<td>英镑(pound)</td>
<td>&amp;pound;</td>
<td>&amp;#163;</td>
</tr>
<tr>
<td>¥</td>
<td>元(yen)</td>
<td>&amp;yen;</td>
<td>&amp;#165;</td>
</tr>
<tr>
<td>€</td>
<td>欧元(euro)</td>
<td>&amp;euro;</td>
<td>&amp;#8364;</td>
</tr>
<tr>
<td>©</td>
<td>版权(copyright)</td>
<td>&amp;copy;</td>
<td>&amp;#169;</td>
</tr>
<tr>
<td>®</td>
<td>注册商标</td>
<td>&amp;reg;</td>
<td>&amp;#174;</td>
</tr>
<tr>
<td>™</td>
<td>商标</td>
<td>&amp;trade;</td>
<td>&amp;#8482;</td>
</tr>
<tr>
<td>×</td>
<td>乘号</td>
<td>&amp;times;</td>
<td>&amp;#215;</td>
</tr>
<tr>
<td>÷</td>
<td>除号</td>
<td>&amp;divide;</td>
<td>&amp;#247;</td>
</tr>
</tbody>
</table>
<h2 id="二、基本标签" tabindex="-1"><a class="header-anchor" href="#二、基本标签"><span>二、基本标签</span></a></h2>
<table>
<thead>
<tr>
<th>标签名</th>
<th>标签语义</th>
<th>属性</th>
</tr>
</thead>
<tbody>
<tr>
<td>h1~h6</td>
<td>标题</td>
<td></td>
</tr>
<tr>
<td>p</td>
<td>段落</td>
<td></td>
</tr>
<tr>
<td>div</td>
<td>无含义用于整体布局</td>
<td></td>
</tr>
<tr>
<td>span</td>
<td>没有语义的通用容器</td>
<td></td>
</tr>
<tr>
<td>em</td>
<td>着重内容</td>
<td></td>
</tr>
<tr>
<td>strong</td>
<td>更重要的内容</td>
<td></td>
</tr>
<tr>
<td>del</td>
<td>删除线</td>
<td></td>
</tr>
<tr>
<td>ins</td>
<td>下划线</td>
<td></td>
</tr>
<tr>
<td>mark</td>
<td>高亮</td>
<td></td>
</tr>
<tr>
<td>br</td>
<td>换行</td>
<td></td>
</tr>
<tr>
<td>hr</td>
<td>分隔</td>
<td>alige 水平对齐<br>size 水平粗细<br>color 颜色<br>width 宽度</td>
</tr>
<tr>
<td>pre</td>
<td>按原文显示</td>
<td></td>
</tr>
</tbody>
</table>
<h2 id="三、列表元素" tabindex="-1"><a class="header-anchor" href="#三、列表元素"><span>三、列表元素</span></a></h2>
<table>
<thead>
<tr>
<th>标签名</th>
<th>标签语义</th>
<th>属性</th>
</tr>
</thead>
<tbody>
<tr>
<td>ul</td>
<td>无序列表</td>
<td></td>
</tr>
<tr>
<td>ol</td>
<td>有序列表</td>
<td></td>
</tr>
<tr>
<td>li</td>
<td>列表项</td>
<td></td>
</tr>
<tr>
<td>dl</td>
<td>列表定义</td>
<td></td>
</tr>
<tr>
<td>dt</td>
<td>列表定义标题</td>
<td></td>
</tr>
<tr>
<td>dd</td>
<td>列表定义内容</td>
<td></td>
</tr>
</tbody>
</table>
<table>
<thead>
<tr>
<th>标签名</th>
<th>标签语义</th>
<th>属性</th>
</tr>
</thead>
<tbody>
<tr>
<td>table</td>
<td>表格</td>
<td>width ：设置表格宽度。<br> height ：设置表格最小高度，表格最终高度可能比设置的值大。<br> border ：设置表格边框宽度。<br> cellspacing ： 设置单元格之间的间距</td>
</tr>
<tr>
<td>thead</td>
<td>表格头部</td>
<td></td>
</tr>
<tr>
<td>tbody</td>
<td>表格主体</td>
<td></td>
</tr>
<tr>
<td>tfoot</td>
<td>表格尾部</td>
<td></td>
</tr>
<tr>
<td>tr</td>
<td>表格行</td>
<td></td>
</tr>
<tr>
<td>td</td>
<td>表格单元格</td>
<td>rowspan ：指定要跨的行数。<br> colspan ：指定要跨的列数。</td>
</tr>
<tr>
<td>caption</td>
<td>表格标题</td>
<td></td>
</tr>
<tr>
<td>th</td>
<td>表格表头</td>
<td></td>
</tr>
<tr>
<td>td</td>
<td>表格内容</td>
<td></td>
</tr>
</tbody>
</table>
<h2 id="四、结构元素" tabindex="-1"><a class="header-anchor" href="#四、结构元素"><span>四、结构元素</span></a></h2>
<table>
<thead>
<tr>
<th>元素名</th>
<th>解释</th>
<th>作用</th>
</tr>
</thead>
<tbody>
<tr>
<td>header</td>
<td>头部</td>
<td>放置logo、搜索框、菜单</td>
</tr>
<tr>
<td>nav</td>
<td>导航</td>
<td>提供页面或网站的主要导航链接</td>
</tr>
<tr>
<td>section</td>
<td>节</td>
<td>表示文档中的独立部分，如章节、页眉、页脚等</td>
</tr>
<tr>
<td>article</td>
<td>文章</td>
<td>表示文档或页面中的独立内容，如新闻文章、博客条目等</td>
</tr>
<tr>
<td>aside</td>
<td>侧边栏</td>
<td>包含与主要内容相关但可以被独立出来的信息，如侧边栏</td>
</tr>
<tr>
<td>footer</td>
<td>底部</td>
<td>通常包含版权信息、联系信息等底部内容</td>
</tr>
</tbody>
</table>
<h2 id="五、分组元素" tabindex="-1"><a class="header-anchor" href="#五、分组元素"><span>五、分组元素</span></a></h2>
<table>
<thead>
<tr>
<th>元素名</th>
<th>含义</th>
<th>作用</th>
</tr>
</thead>
<tbody>
<tr>
<td>figure</td>
<td>图片</td>
<td>用于标记图片、图表或其他媒体的内容</td>
</tr>
<tr>
<td>figcaption</td>
<td>图片标题</td>
<td>为figure元素内的内容提供标题或说明</td>
</tr>
<tr>
<td>hgroup</td>
<td>表格分组</td>
<td>表格分组，用于将表格中的行、列、表头等分组，以方便对表格进行样式设置</td>
</tr>
</tbody>
</table>
<h2 id="六、交互元素" tabindex="-1"><a class="header-anchor" href="#六、交互元素"><span>六、交互元素</span></a></h2>
<table>
<thead>
<tr>
<th>元素名</th>
<th>解释</th>
<th>属性值</th>
<th>作用</th>
</tr>
</thead>
<tbody>
<tr>
<td>details</td>
<td>详情</td>
<td></td>
<td>用于创建一个可以显示或隐藏详细信息的可折叠面板</td>
</tr>
<tr>
<td>summary</td>
<td>详情标题</td>
<td></td>
<td>作为details元素的标题，通常可点击以展开/折叠details内容</td>
</tr>
<tr>
<td>progress</td>
<td>进度条</td>
<td>value 现有量<br>max 总量</td>
<td>用于显示一个任务或操作的进度</td>
</tr>
<tr>
<td>meter</td>
<td>仪表盘</td>
<td>optimum 定义最佳值 <br>min 最小值<br>max 最大值<br>low 低值<br>high 高值<br>value 现有值</td>
<td>用于显示一个值在预定义范围中的位置，如进度条</td>
</tr>
</tbody>
</table>
<h2 id="七、语义元素" tabindex="-1"><a class="header-anchor" href="#七、语义元素"><span>七、语义元素</span></a></h2>
<table>
<thead>
<tr>
<th>元素名</th>
<th>解释</th>
<th>作用</th>
</tr>
</thead>
<tbody>
<tr>
<td>time</td>
<td>时间</td>
<td>用于表示时间和日期<br>datetime 时间戳<br>pubdate 发布时间</td>
</tr>
<tr>
<td>mark</td>
<td>标记</td>
<td>用于突出显示文本片段，如搜索结果</td>
</tr>
<tr>
<td>cite</td>
<td>引用</td>
<td>用于表示引用内容，如作者、作品等</td>
</tr>
</tbody>
</table>
<h2 id="八、表单元素" tabindex="-1"><a class="header-anchor" href="#八、表单元素"><span>八、表单元素</span></a></h2>
<table>
<thead>
<tr>
<th>标签名</th>
<th>含义</th>
<th>属性值</th>
<th>单/双</th>
<th>块/行</th>
</tr>
</thead>
<tbody>
<tr>
<td>img</td>
<td>图片</td>
<td>src 图片路径<br> alt 图片描述<br> width 图片宽度<br> height 图片高度<br> border 图片边框</td>
<td>单</td>
<td>块</td>
</tr>
<tr>
<td>a</td>
<td>超链接</td>
<td>href 指定要跳转到的具体目标<br> target 控制跳转时如何打开页面<br>     _self 在本窗口打开<br>     _blank 在新窗口打开<br>id 元素的唯一标识，可用于设置锚点</td>
<td>双</td>
<td>行</td>
</tr>
<tr>
<td>form</td>
<td>表单</td>
<td>action 表单提交地址<br>method 提交方式<br>enctype 表单编码类型<br>novalidate 禁止校验<br>autocomplete 自动完成</td>
<td>双</td>
<td>块</td>
</tr>
<tr>
<td>input</td>
<td>输入框</td>
<td>type 类型<br>    text 单行文本框<br>    password 密码<br>    radio 单选按钮<br>    checkbox 多选按钮<br>    submit 提交按钮<br>    reset 重置按钮<br>    image 图片按钮<br>    hidden 隐藏域 <br>name 标识<br>value 默认值<br>placeholder 提示信息<br>disabled 禁止输入<br>readonly 只读<br>checked 默认选中<br>autofocus 自动获取焦点<br>autocomplete 自动完成<br>required 必填<br>maxlength 最大长度<br>min 最小值<br>max 最大值<br>step 步长<br>accept 文件类型<br>multiple 多选<br>size 宽度<br>list 列表<br>form 表单id<br></td>
<td>单</td>
<td>行</td>
</tr>
<tr>
<td>textarea</td>
<td>多行文本框</td>
<td>rows 行数<br>cols 列数<br>placeholder 提示信息<br>disabled 禁止输入<br>readonly 只读<br>autofocus 自动获取焦点<br>autocomplete 自动完成<br>required 必填<br>maxlength 最大长度<br>min 最小值<br>max 最大值<br>step 步长<br>list 列表<br>form 表单id<br></td>
<td>单</td>
<td>行</td>
</tr>
<tr>
<td>select</td>
<td>下拉框</td>
<td>name 标识<br>value 默认值<br>multiple 多选<br>size 显示行数<br>disabled 禁止选择<br>autofocus 自动获取焦点<br>autocomplete 自动完成<br>required 必填<br>list 列表<br>form 表单id<br></td>
<td>单</td>
<td>行</td>
</tr>
</tbody>
</table>
<h2 id="九、多媒体元素" tabindex="-1"><a class="header-anchor" href="#九、多媒体元素"><span>九、多媒体元素</span></a></h2>
<table>
<thead>
<tr>
<th>元素名</th>
<th>含义</th>
<th>属性值</th>
</tr>
</thead>
<tbody>
<tr>
<td>audio</td>
<td>音频</td>
<td>src 音频路径</td>
</tr>
<tr>
<td>video</td>
<td>视频</td>
<td>src 视频路径</td>
</tr>
<tr>
<td>source</td>
<td>音频/视频源</td>
<td>src 音频/视频路径<br>type 音频/视频类型</td>
</tr>
<tr>
<td>track</td>
<td>字幕</td>
<td>src 字幕路径<br>kind 字幕类型<br>label 字幕标签<br>default 默认字幕</td>
</tr>
<tr>
<td>picture</td>
<td>图片</td>
<td></td>
</tr>
</tbody>
</table>
<h2 id="十、全局属性" tabindex="-1"><a class="header-anchor" href="#十、全局属性"><span>十、全局属性</span></a></h2>
<table>
<thead>
<tr>
<th>属性名</th>
<th>含义</th>
<th>属性值</th>
</tr>
</thead>
<tbody>
<tr>
<td>draggable</td>
<td>拖动元素</td>
<td>true/false</td>
</tr>
<tr>
<td>contenteditable</td>
<td>可编辑元素</td>
<td>true/false</td>
</tr>
<tr>
<td>hidden</td>
<td>隐藏元素</td>
<td>true/false</td>
</tr>
<tr>
<td>spellcheck</td>
<td>拼写检查</td>
<td>true/false</td>
</tr>
</tbody>
</table>
<h2 id="参考文献" tabindex="-1"><a class="header-anchor" href="#参考文献"><span>参考文献</span></a></h2>
<p>[1] <a href="https://www.w3c.org/" target="_blank" rel="noopener noreferrer">W3C官网<ExternalLinkIcon/></a></p>
<p>[2] <a href="https://www.w3school.com.cn/" target="_blank" rel="noopener noreferrer">w3school<ExternalLinkIcon/></a></p>
<p>[3] <a href="https://developer.mozilla.org/zh-CN/docs/Web/HTML" target="_blank" rel="noopener noreferrer">MDN<ExternalLinkIcon/></a></p>
</div></template>


