<template><div><h2 id="html基础" tabindex="-1"><a class="header-anchor" href="#html基础"><span>HTML基础</span></a></h2>
<h3 id="_1-文档基本格式" tabindex="-1"><a class="header-anchor" href="#_1-文档基本格式"><span>1.文档基本格式</span></a></h3>
<div class="language-text line-numbers-mode" data-ext="text" data-title="text"><pre v-pre class="language-text"><code>&lt;!DOCTYPE html> 
&lt;html lang="zh-CN"> 
&lt;head> 
&lt;meta charset="UTF-8"> 
&lt;title>document&lt;/title> 
&lt;/head> 
&lt;body> 
&lt;/body> 
&lt;/html>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_2-基本概念" tabindex="-1"><a class="header-anchor" href="#_2-基本概念"><span>2.基本概念</span></a></h3>
<table>
<thead>
<tr>
<th>概念</th>
<th>描述</th>
<th>举例</th>
</tr>
</thead>
<tbody>
<tr>
<td>单标签</td>
<td>只能有一个开始标记</td>
<td><code v-pre>&lt;hr /&gt;</code></td>
</tr>
<tr>
<td>双标签</td>
<td>开始标记和结束标记</td>
<td><code v-pre>&lt;p&gt;&lt;/p&gt;</code></td>
</tr>
<tr>
<td>行内元素</td>
<td>独占一行</td>
<td></td>
</tr>
<tr>
<td>块元素</td>
<td>不独占一行</td>
<td></td>
</tr>
<tr>
<td>文档声明</td>
<td>告诉浏览器当前网页版本</td>
<td><code v-pre>&lt;!DOCTYPE html&gt;</code></td>
</tr>
<tr>
<td>字符编码</td>
<td>声明文档编码，一般为UTF-8</td>
<td><code v-pre>&lt;meta charset=&quot;UTF-8&quot;&gt;</code></td>
</tr>
<tr>
<td>设置语言</td>
<td>告诉浏览器当前网页语言</td>
<td><code v-pre>&lt;!DOCTYPE html&gt;&lt;html lang=&quot;zh-CN&quot;&gt;</code></td>
</tr>
<tr>
<td>id</td>
<td>给标签指定唯一标识</td>
<td>id不能重复</td>
</tr>
<tr>
<td>class</td>
<td>给标签指定类名</td>
<td></td>
</tr>
<tr>
<td>style</td>
<td>给标签设置CSS样式</td>
<td></td>
</tr>
<tr>
<td>dir</td>
<td>内容的方向，值：ltr、rtl</td>
<td></td>
</tr>
<tr>
<td>title</td>
<td>给标签设置一个文字提示</td>
<td></td>
</tr>
<tr>
<td>lang</td>
<td>给标签指定语言</td>
<td></td>
</tr>
</tbody>
</table>
<h3 id="_3-字符编码" tabindex="-1"><a class="header-anchor" href="#_3-字符编码"><span>3.字符编码</span></a></h3>
<table>
<thead>
<tr>
<th>charset</th>
<th>解释</th>
</tr>
</thead>
<tbody>
<tr>
<td>ASCII</td>
<td>大写字母、小写字母、数字、一些符号，共计128个</td>
</tr>
<tr>
<td>ISO 8859-1</td>
<td>在 ASCII 基础上，扩充了一些希腊字符等，共计是256个</td>
</tr>
<tr>
<td>GB2312</td>
<td>继续扩充，收录了 6763 个常用汉字、682个字符</td>
</tr>
<tr>
<td>GBK</td>
<td>收录了的汉字和符号达到 20000+ ，支持繁体中文</td>
</tr>
<tr>
<td>UTF-8</td>
<td>包含世界上所有语言的：所有文字与符号。—— 很常用</td>
</tr>
</tbody>
</table>
<pre><code>存储时采用哪种方式编码 ，读取时就采用哪种方式解码
编写 html 文件时，统一用 UFT-8 编码
</code></pre>
<h3 id="_4-设置语言" tabindex="-1"><a class="header-anchor" href="#_4-设置语言"><span>4.设置语言</span></a></h3>
<table>
<thead>
<tr>
<th>lang</th>
<th>解释</th>
</tr>
</thead>
<tbody>
<tr>
<td>zh-CN</td>
<td>中文-中国大陆（简体中文）</td>
</tr>
<tr>
<td>zh-TW</td>
<td>中文-中国台湾（繁体中文）</td>
</tr>
<tr>
<td>zh</td>
<td>中文</td>
</tr>
<tr>
<td>en-US</td>
<td>英语-美国</td>
</tr>
<tr>
<td>en-GB</td>
<td>英语-英国</td>
</tr>
</tbody>
</table>
<h3 id="_5-特殊字符" tabindex="-1"><a class="header-anchor" href="#_5-特殊字符"><span>5.特殊字符</span></a></h3>
<table>
<thead>
<tr>
<th>符号</th>
<th>含义</th>
<th>实体名称</th>
<th>实体编号</th>
</tr>
</thead>
<tbody>
<tr>
<td></td>
<td>空格</td>
<td>&amp;nbsp;</td>
<td>&amp;#160;</td>
</tr>
<tr>
<td>&lt;</td>
<td>小于号</td>
<td>&amp;lt;</td>
<td>&amp;#60;</td>
</tr>
<tr>
<td>&gt;</td>
<td>大于号</td>
<td>&amp;gt;</td>
<td>&amp;#62;</td>
</tr>
<tr>
<td>&amp;</td>
<td>和号</td>
<td>&amp;amp;</td>
<td>&amp;#38;</td>
</tr>
<tr>
<td>&quot;</td>
<td>引号</td>
<td>&amp;quot;</td>
<td>&amp;#34;</td>
</tr>
<tr>
<td>`</td>
<td>反引号</td>
<td>&amp;acute;</td>
<td>&amp;#180;</td>
</tr>
<tr>
<td>£</td>
<td>英镑(pound)</td>
<td>&amp;pound;</td>
<td>&amp;#163;</td>
</tr>
<tr>
<td>¥</td>
<td>元(yen)</td>
<td>&amp;yen;</td>
<td>&amp;#165;</td>
</tr>
<tr>
<td>€</td>
<td>欧元(euro)</td>
<td>&amp;euro;</td>
<td>&amp;#8364;</td>
</tr>
<tr>
<td>©</td>
<td>版权(copyright)</td>
<td>&amp;copy;</td>
<td>&amp;#169;</td>
</tr>
<tr>
<td>®</td>
<td>注册商标</td>
<td>&amp;reg;</td>
<td>&amp;#174;</td>
</tr>
<tr>
<td>™</td>
<td>商标</td>
<td>&amp;trade;</td>
<td>&amp;#8482;</td>
</tr>
<tr>
<td>×</td>
<td>乘号</td>
<td>&amp;times;</td>
<td>&amp;#215;</td>
</tr>
<tr>
<td>÷</td>
<td>除号</td>
<td>&amp;divide;</td>
<td>&amp;#247;</td>
</tr>
</tbody>
</table>
<h3 id="_6-实体字符" tabindex="-1"><a class="header-anchor" href="#_6-实体字符"><span>6.实体字符</span></a></h3>
<table>
<thead>
<tr>
<th>符号</th>
<th>描述</th>
<th>实体名称</th>
<th>实体编号</th>
</tr>
</thead>
<tbody>
<tr>
<td></td>
<td>空格</td>
<td>&amp;nbsp;</td>
<td>&amp;#160;</td>
</tr>
<tr>
<td>&lt;</td>
<td>小于号</td>
<td>&amp;lt;</td>
<td>&amp;#60;</td>
</tr>
<tr>
<td>&gt;</td>
<td>大于号</td>
<td>&amp;gt;</td>
<td>&amp;#62;</td>
</tr>
<tr>
<td>&amp;</td>
<td>和号</td>
<td>&amp;amp;</td>
<td>&amp;#38;</td>
</tr>
<tr>
<td>lI</td>
<td>引号</td>
<td>&amp;quot;</td>
<td>&amp;#34;</td>
</tr>
<tr>
<td>´</td>
<td>反引号</td>
<td>&amp;acute;</td>
<td>&amp;#180;</td>
</tr>
<tr>
<td>4</td>
<td>分(cent)</td>
<td>&amp;cent;</td>
<td>&amp;#162;</td>
</tr>
<tr>
<td>f</td>
<td>镑(pound)</td>
<td>&amp;pound;</td>
<td>&amp;#163;</td>
</tr>
<tr>
<td>¥</td>
<td>元(yen)</td>
<td>&amp;yen;</td>
<td>&amp;#165;</td>
</tr>
<tr>
<td>E</td>
<td>欧元(euro)</td>
<td>&amp;euro;</td>
<td>&amp;#8364;</td>
</tr>
<tr>
<td>O</td>
<td>版权(copyright)</td>
<td>&amp;copy;</td>
<td>&amp;#169;</td>
</tr>
<tr>
<td>@</td>
<td>注册商标</td>
<td>&amp;reg;</td>
<td>&amp;#174;</td>
</tr>
<tr>
<td>TM</td>
<td>商标</td>
<td>&amp;trade;</td>
<td>&amp;#8482;</td>
</tr>
<tr>
<td>×</td>
<td>乘号</td>
<td>&amp;times</td>
<td>&amp;#215;</td>
</tr>
<tr>
<td>÷</td>
<td>除号</td>
<td>&amp;divide;</td>
<td>&amp;#247;</td>
</tr>
</tbody>
</table>
</div></template>


